import 'package:flutter/material.dart';
import 'dart:math';

void main() {
  runApp(WordleApp());
}

class WordleApp extends StatelessWidget {
  const WordleApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Wordle',
      theme: ThemeData(primarySwatch: Colors.purple),
      home: WordleGame(),
    );
  }
}

class WordleGame extends StatefulWidget {
  const WordleGame({super.key});

  @override
  _WordleGameState createState() => _WordleGameState();
}

class _WordleGameState extends State<WordleGame> {
  final List<String> dictionary = [
    'HELLO',
    'ABOUT',
    'ALERT',
    'ARGUE',
    'BEACH',
    'ABOVE',
    'ALIKE',
    'ARISE',
    'BEGAN',
    'ABUSE',
    'ALIVE',
    'ARRAY',
    'BEGIN',
    'ACTOR',
    'ALLOW',
    'ASIDE',
    'BEGUN',
    'ACUTE',
    'ALONE',
    'ASSET',
    'BEING',
    'ADMIT',
    'ALONG',
    'AUDIO',
    'BELOW',
    'ADOPT',
    'ALTER',
    'AUDIT',
    'BENCH',
    'ADULT',
    'AMONG',
    'AVOID',
    'BILLY',
    'AFTER',
    'ANGER',
    'AWARD',
    'BIRTH',
    'AGAIN',
    'ANGLE',
    'AWARE',
    'BLACK',
    'AGENT',
    'ANGRY',
    'BADLY',
    'BLAME',
    'AGREE',
    'APART',
    'BAKER',
    'BLIND',
    'AHEAD',
    'APPLE',
    'BASES',
    'BLOCK',
    'ALARM',
    'APPLY',
    'BASIC',
    'BLOOD',
    'ALBUM',
    'ARENA',
    'BASIS',
    'BOARD',
    'BOOST',
    'BUYER',
    'CHINA',
    'COVER',
    'BOOTH',
    'CABLE',
    'CHOSE',
    'CRAFT',
    'BOUND',
    'CALIF',
    'CIVIL',
    'CRASH',
    'BRAIN',
    'CARRY',
    'CLAIM',
    'CREAM',
    'BRAND',
    'CATCH',
    'CLASS',
    'CRIME',
    'BREAD',
    'CAUSE',
    'CLEAN',
    'CROSS',
    'BREAK',
    'CHAIN',
    'CLEAR',
    'CROWD',
    'BREED',
    'CHAIR',
    'CLICK',
    'CROWN',
    'BRIEF',
    'CHART',
    'CLOCK',
    'CURVE',
    'BRING',
    'CHASE',
    'CLOSE',
    'CYCLE',
    'BROAD',
    'CHEAP',
    'COACH',
    'DAILY',
    'BROKE',
    'CHECK',
    'COAST',
    'DANCE',
    'BROWN',
    'CHEST',
    'COULD',
    'DATED',
    'BUILD',
    'CHIEF',
    'COUNT',
    'DEALT',
    'BUILT',
    'CHILD',
    'COURT',
    'DEATH',
    'DEBUT',
    'ENTRY',
    'FORTH',
    'GROUP',
    'DELAY',
    'EQUAL',
    'FORTY',
    'GROWN',
    'DEPTH',
    'ERROR',
    'FORUM',
    'GUARD',
    'DOING',
    'EVENT',
    'FOUND',
    'GUESS',
    'DOUBT',
    'EVERY',
    'FRAME',
    'GUEST',
    'DOZEN',
    'EXACT',
    'FRANK',
    'GUIDE',
    'DRAFT',
    'EXIST',
    'FRAUD',
    'HAPPY',
    'DRAMA',
    'EXTRA',
    'FRESH',
    'HARRY',
    'DRAWN',
    'FAITH',
    'FRONT',
    'HEART',
    'DREAM',
    'FALSE',
    'FRUIT',
    'HEAVY',
    'DRESS',
    'FAULT',
    'FULLY',
    'HENCE',
    'DRILL',
    'FIBRE',
    'FUNNY',
    'NIGHT',
    'DRINK',
    'FIELD',
    'GIANT',
    'HORSE',
    'DRIVE',
    'FIFTH',
    'GIVEN',
    'HOTEL',
    'DROVE',
    'FIFTY',
    'GLASS',
    'HOUSE',
    'DYING',
    'FIGHT',
    'GLOBE',
    'HUMAN',
    'EAGER',
    'FINAL',
    'GOING',
    'IDEAL',
    'EARLY',
    'FIRST',
    'GRACE',
    'IMAGE',
    'EARTH',
    'FIXED',
    'GRADE',
    'INDEX',
    'EIGHT',
    'FLASH',
    'GRAND',
    'INNER',
    'ELITE',
    'FLEET',
    'GRANT',
    'INPUT',
    'EMPTY',
    'FLOOR',
    'GRASS',
    'ISSUE',
    'ENEMY',
    'FLUID',
    'GREAT',
    'IRONY',
    'ENJOY',
    'FOCUS',
    'GREEN',
    'JUICE',
    'ENTER',
    'FORCE',
    'GROSS',
    'JOINT',
    'JUDGE',
    'METAL',
    'MEDIA',
    'NEWLY',
    'KNOWN',
    'LOCAL',
    'MIGHT',
    'NOISE',
    'LABEL',
    'LOGIC',
    'MINOR',
    'NORTH',
    'LARGE',
    'LOOSE',
    'MINUS',
    'NOTED',
    'LASER',
    'LOWER',
    'MIXED',
    'NOVEL',
    'LATER',
    'LUCKY',
    'MODEL',
    'NURSE',
    'LAUGH',
    'LUNCH',
    'MONEY',
    'OCCUR',
    'LAYER',
    'LYING',
    'MONTH',
    'OCEAN',
    'LEARN',
    'MAGIC',
    'MORAL',
    'OFFER',
    'LEASE',
    'MAJOR',
    'MOTOR',
    'OFTEN',
    'LEAST',
    'MAKER',
    'MOUNT',
    'ORDER',
    'LEAVE',
    'MARCH',
    'MOUSE',
    'OTHER',
    'LEGAL',
    'MUSIC',
    'MOUTH',
    'OUGHT',
    'LEVEL',
    'MATCH',
    'MOVIE',
    'PAINT',
    'LIGHT',
    'MAYOR',
    'NEEDS',
    'PAPER',
    'PEACE',
    'POWER',
    'RADIO',
    'ROUND',
    'PANEL',
    'PRESS',
    'RAISE',
    'ROUTE',
    'PHASE',
    'PRICE',
    'RANGE',
    'ROYAL',
    'PHONE',
    'PRIDE',
    'RAPID',
    'RURAL',
    'PHOTO',
    'PRIME',
    'RATIO',
    'SCALE',
    'PIECE',
    'PRINT',
    'REACH',
    'SCENE',
    'PILOT',
    'PRIOR',
    'READY',
    'SCOPE',
    'PITCH',
    'PRIZE',
    'REFER',
    'SCORE',
    'PLACE',
    'PROOF',
    'RIGHT',
    'SENSE',
    'PLAIN',
    'PROUD',
    'RIVAL',
    'SERVE',
    'PLANE',
    'PROVE',
    'RIVER',
    'SEVEN',
    'PLANT',
    'QUEEN',
    'QUICK',
    'SHALL',
    'PLATE',
    'SIXTH',
    'STAND',
    'SHAPE',
    'POINT',
    'QUIET',
    'ROMAN',
    'SHARE',
    'POUND',
    'QUITE',
    'ROUGH',
    'SHARP',
    'SHEET',
    'SPARE',
    'STYLE',
    'TIMES',
    'SHELF',
    'SPEAK',
    'SUGAR',
    'TIRED',
    'SHELL',
    'SPEED',
    'SUITE',
    'TITLE',
    'SHIFT',
    'SPEND',
    'SUPER',
    'TODAY',
    'SHIRT',
    'SPENT',
    'SWEET',
    'TOPIC',
    'SHOCK',
    'SPLIT',
    'TABLE',
    'TOTAL',
    'SHOOT',
    'SPOKE',
    'TAKEN',
    'TOUCH',
    'SHORT',
    'SPORT',
    'TASTE',
    'TOUGH',
    'SHOWN',
    'STAFF',
    'TAXES',
    'TOWER',
    'SIGHT',
    'STAGE',
    'TEACH',
    'TRACK',
    'SINCE',
    'STAKE',
    'TEETH',
    'TRADE',
    'SIXTY',
    'START',
    'TEXAS',
    'TREAT',
    'SIZED',
    'STATE',
    'THANK',
    'TREND',
    'SKILL',
    'STEAM',
    'THEFT',
    'TRIAL',
    'SLEEP',
    'STEEL',
    'THEIR',
    'TRIED',
    'SLIDE',
    'STICK',
    'THEME',
    'TRIES',
    'SMALL',
    'STILL',
    'THERE',
    'TRUCK',
    'SMART',
    'STOCK',
    'THESE',
    'TRULY',
    'SMILE',
    'STONE',
    'THICK',
    'TRUST',
    'SMITH',
    'STOOD',
    'THING',
    'TRUTH',
    'SMOKE',
    'STORE',
    'THINK',
    'TWICE',
    'SOLID',
    'STORM',
    'THIRD',
    'UNDER',
    'SOLVE',
    'STORY',
    'THOSE',
    'UNDUE',
    'SORRY',
    'STRIP',
    'THREE',
    'UNION',
    'SOUND',
    'STUDY',
    'THROW',
    'UNTIL',
    'SPACE',
    'STUFF',
    'TIGHT',
    'UPPER',
    'UPSET',
    'WHOLE',
    'WASTE',
    'WOUND',
    'URBAN',
    'WHOSE',
    'WATCH',
    'WRITE',
    'USAGE',
    'WOMAN',
    'WATER',
    'WRONG',
    'USUAL',
    'TRAIN',
    'WHEEL',
    'WROTE',
    'VALID',
    'WORLD',
    'WHERE',
    'YIELD',
    'VALUE',
    'WORRY',
    'WHICH',
    'YOUNG',
    'VIDEO',
    'WORSE',
    'WHILE',
    'YOUTH',
    'VIRUS',
    'WORST',
    'WHITE',
    'WORTH',
    'VISIT',
    'WOULD',
    'VITAL',
    'VOICE'
  ];

  final String secret = [
    'HELLO',
    'ABOUT',
    'ALERT',
    'ARGUE',
    'BEACH',
    'ABOVE',
    'ALIKE',
    'ARISE',
    'BEGAN',
    'ABUSE',
    'ALIVE',
    'ARRAY',
    'BEGIN',
    'ACTOR',
    'ALLOW',
    'ASIDE',
    'BEGUN',
    'ACUTE',
    'ALONE',
    'ASSET',
    'BEING',
    'ADMIT',
    'ALONG',
    'AUDIO',
    'BELOW',
    'ADOPT',
    'ALTER',
    'AUDIT',
    'BENCH',
    'ADULT',
    'AMONG',
    'AVOID',
    'BILLY',
    'AFTER',
    'ANGER',
    'AWARD',
    'BIRTH',
    'AGAIN',
    'ANGLE',
    'AWARE',
    'BLACK',
    'AGENT',
    'ANGRY',
    'BADLY',
    'BLAME',
    'AGREE',
    'APART',
    'BAKER',
    'BLIND',
    'AHEAD',
    'APPLE',
    'BASES',
    'BLOCK',
    'ALARM',
    'APPLY',
    'BASIC',
    'BLOOD',
    'ALBUM',
    'ARENA',
    'BASIS',
    'BOARD',
    'BOOST',
    'BUYER',
    'CHINA',
    'COVER',
    'BOOTH',
    'CABLE',
    'CHOSE',
    'CRAFT',
    'BOUND',
    'CALIF',
    'CIVIL',
    'CRASH',
    'BRAIN',
    'CARRY',
    'CLAIM',
    'CREAM',
    'BRAND',
    'CATCH',
    'CLASS',
    'CRIME',
    'BREAD',
    'CAUSE',
    'CLEAN',
    'CROSS',
    'BREAK',
    'CHAIN',
    'CLEAR',
    'CROWD',
    'BREED',
    'CHAIR',
    'CLICK',
    'CROWN',
    'BRIEF',
    'CHART',
    'CLOCK',
    'CURVE',
    'BRING',
    'CHASE',
    'CLOSE',
    'CYCLE',
    'BROAD',
    'CHEAP',
    'COACH',
    'DAILY',
    'BROKE',
    'CHECK',
    'COAST',
    'DANCE',
    'BROWN',
    'CHEST',
    'COULD',
    'DATED',
    'BUILD',
    'CHIEF',
    'COUNT',
    'DEALT',
    'BUILT',
    'CHILD',
    'COURT',
    'DEATH',
    'DEBUT',
    'ENTRY',
    'FORTH',
    'GROUP',
    'DELAY',
    'EQUAL',
    'FORTY',
    'GROWN',
    'DEPTH',
    'ERROR',
    'FORUM',
    'GUARD',
    'DOING',
    'EVENT',
    'FOUND',
    'GUESS',
    'DOUBT',
    'EVERY',
    'FRAME',
    'GUEST',
    'DOZEN',
    'EXACT',
    'FRANK',
    'GUIDE',
    'DRAFT',
    'EXIST',
    'FRAUD',
    'HAPPY',
    'DRAMA',
    'EXTRA',
    'FRESH',
    'HARRY',
    'DRAWN',
    'FAITH',
    'FRONT',
    'HEART',
    'DREAM',
    'FALSE',
    'FRUIT',
    'HEAVY',
    'DRESS',
    'FAULT',
    'FULLY',
    'HENCE',
    'DRILL',
    'FIBRE',
    'FUNNY',
    'NIGHT',
    'DRINK',
    'FIELD',
    'GIANT',
    'HORSE',
    'DRIVE',
    'FIFTH',
    'GIVEN',
    'HOTEL',
    'DROVE',
    'FIFTY',
    'GLASS',
    'HOUSE',
    'DYING',
    'FIGHT',
    'GLOBE',
    'HUMAN',
    'EAGER',
    'FINAL',
    'GOING',
    'IDEAL',
    'EARLY',
    'FIRST',
    'GRACE',
    'IMAGE',
    'EARTH',
    'FIXED',
    'GRADE',
    'INDEX',
    'EIGHT',
    'FLASH',
    'GRAND',
    'INNER',
    'ELITE',
    'FLEET',
    'GRANT',
    'INPUT',
    'EMPTY',
    'FLOOR',
    'GRASS',
    'ISSUE',
    'ENEMY',
    'FLUID',
    'GREAT',
    'IRONY',
    'ENJOY',
    'FOCUS',
    'GREEN',
    'JUICE',
    'ENTER',
    'FORCE',
    'GROSS',
    'JOINT',
    'JUDGE',
    'METAL',
    'MEDIA',
    'NEWLY',
    'KNOWN',
    'LOCAL',
    'MIGHT',
    'NOISE',
    'LABEL',
    'LOGIC',
    'MINOR',
    'NORTH',
    'LARGE',
    'LOOSE',
    'MINUS',
    'NOTED',
    'LASER',
    'LOWER',
    'MIXED',
    'NOVEL',
    'LATER',
    'LUCKY',
    'MODEL',
    'NURSE',
    'LAUGH',
    'LUNCH',
    'MONEY',
    'OCCUR',
    'LAYER',
    'LYING',
    'MONTH',
    'OCEAN',
    'LEARN',
    'MAGIC',
    'MORAL',
    'OFFER',
    'LEASE',
    'MAJOR',
    'MOTOR',
    'OFTEN',
    'LEAST',
    'MAKER',
    'MOUNT',
    'ORDER',
    'LEAVE',
    'MARCH',
    'MOUSE',
    'OTHER',
    'LEGAL',
    'MUSIC',
    'MOUTH',
    'OUGHT',
    'LEVEL',
    'MATCH',
    'MOVIE',
    'PAINT',
    'LIGHT',
    'MAYOR',
    'NEEDS',
    'PAPER',
    'PEACE',
    'POWER',
    'RADIO',
    'ROUND',
    'PANEL',
    'PRESS',
    'RAISE',
    'ROUTE',
    'PHASE',
    'PRICE',
    'RANGE',
    'ROYAL',
    'PHONE',
    'PRIDE',
    'RAPID',
    'RURAL',
    'PHOTO',
    'PRIME',
    'RATIO',
    'SCALE',
    'PIECE',
    'PRINT',
    'REACH',
    'SCENE',
    'PILOT',
    'PRIOR',
    'READY',
    'SCOPE',
    'PITCH',
    'PRIZE',
    'REFER',
    'SCORE',
    'PLACE',
    'PROOF',
    'RIGHT',
    'SENSE',
    'PLAIN',
    'PROUD',
    'RIVAL',
    'SERVE',
    'PLANE',
    'PROVE',
    'RIVER',
    'SEVEN',
    'PLANT',
    'QUEEN',
    'QUICK',
    'SHALL',
    'PLATE',
    'SIXTH',
    'STAND',
    'SHAPE',
    'POINT',
    'QUIET',
    'ROMAN',
    'SHARE',
    'POUND',
    'QUITE',
    'ROUGH',
    'SHARP',
    'SHEET',
    'SPARE',
    'STYLE',
    'TIMES',
    'SHELF',
    'SPEAK',
    'SUGAR',
    'TIRED',
    'SHELL',
    'SPEED',
    'SUITE',
    'TITLE',
    'SHIFT',
    'SPEND',
    'SUPER',
    'TODAY',
    'SHIRT',
    'SPENT',
    'SWEET',
    'TOPIC',
    'SHOCK',
    'SPLIT',
    'TABLE',
    'TOTAL',
    'SHOOT',
    'SPOKE',
    'TAKEN',
    'TOUCH',
    'SHORT',
    'SPORT',
    'TASTE',
    'TOUGH',
    'SHOWN',
    'STAFF',
    'TAXES',
    'TOWER',
    'SIGHT',
    'STAGE',
    'TEACH',
    'TRACK',
    'SINCE',
    'STAKE',
    'TEETH',
    'TRADE',
    'SIXTY',
    'START',
    'TEXAS',
    'TREAT',
    'SIZED',
    'STATE',
    'THANK',
    'TREND',
    'SKILL',
    'STEAM',
    'THEFT',
    'TRIAL',
    'SLEEP',
    'STEEL',
    'THEIR',
    'TRIED',
    'SLIDE',
    'STICK',
    'THEME',
    'TRIES',
    'SMALL',
    'STILL',
    'THERE',
    'TRUCK',
    'SMART',
    'STOCK',
    'THESE',
    'TRULY',
    'SMILE',
    'STONE',
    'THICK',
    'TRUST',
    'SMITH',
    'STOOD',
    'THING',
    'TRUTH',
    'SMOKE',
    'STORE',
    'THINK',
    'TWICE',
    'SOLID',
    'STORM',
    'THIRD',
    'UNDER',
    'SOLVE',
    'STORY',
    'THOSE',
    'UNDUE',
    'SORRY',
    'STRIP',
    'THREE',
    'UNION',
    'SOUND',
    'STUDY',
    'THROW',
    'UNTIL',
    'SPACE',
    'STUFF',
    'TIGHT',
    'UPPER',
    'UPSET',
    'WHOLE',
    'WASTE',
    'WOUND',
    'URBAN',
    'WHOSE',
    'WATCH',
    'WRITE',
    'USAGE',
    'WOMAN',
    'WATER',
    'WRONG',
    'USUAL',
    'TRAIN',
    'WHEEL',
    'WROTE',
    'VALID',
    'WORLD',
    'WHERE',
    'YIELD',
    'VALUE',
    'WORRY',
    'WHICH',
    'YOUNG',
    'VIDEO',
    'WORSE',
    'WHILE',
    'YOUTH',
    'VIRUS',
    'WORST',
    'WHITE',
    'WORTH',
    'VISIT',
    'WOULD',
    'VITAL',
    'VOICE'
  ][Random().nextInt(5)];

  final List<List<String>> grid =
      List.generate(6, (_) => List.generate(5, (_) => ''));
  int currentRow = 0;
  int currentCol = 0;

  void addLetter(String letter) {
    if (currentCol < 5) {
      setState(() {
        grid[currentRow][currentCol] = letter;
        currentCol++;
      });
    }
  }

  void removeLetter() {
    if (currentCol > 0) {
      setState(() {
        currentCol--;
        grid[currentRow][currentCol] = '';
      });
    }
  }

  void submitWord() {
    if (currentCol < 5) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Word must be 5 letters')),
      );
      return;
    }

    String guess = grid[currentRow].join('');
    if (!dictionary.contains(guess)) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Word not in dictionary')),
      );
      return;
    }

    if (guess == secret) {
      showEndDialog('Congratulations! You guessed the word!');
      return;
    }

    setState(() {
      currentRow++;
      currentCol = 0;
    });

    if (currentRow == 6) {
      showEndDialog('Game Over! The word was $secret.');
    }
  }

  void showEndDialog(String message) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(message),
        actions: [
          TextButton(
            onPressed: () {
              Navigator.of(context).pop();
              resetGame();
            },
            child: const Text('Play Again'),
          ),
        ],
      ),
    );
  }

  void resetGame() {
    setState(() {
      for (var row in grid) {
        row.fillRange(0, row.length, '');
      }
      currentRow = 0;
      currentCol = 0;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Wordle')),
      body: Column(
        children: [
          Expanded(
            child: GridView.builder(
              gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 5,
                mainAxisSpacing: 8,
                crossAxisSpacing: 8,
              ),
              itemCount: 30,
              itemBuilder: (context, index) {
                int row = index ~/ 5;
                int col = index % 5;
                String letter = grid[row][col];
                Color bgColor = Colors.grey;
                if (row < currentRow) {
                  if (secret[col] == letter) {
                    bgColor = Colors.green;
                  } else if (secret.contains(letter)) {
                    bgColor = Colors.yellow;
                  } else {
                    bgColor = Colors.black;
                  }
                }
                return Container(
                  alignment: Alignment.center,
                  decoration: BoxDecoration(
                    color: bgColor,
                    border: Border.all(color: Colors.black),
                  ),
                  child: Text(
                    letter.toUpperCase(),
                    style: const TextStyle(fontSize: 24, color: Colors.white),
                  ),
                );
              },
            ),
          ),
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: Wrap(
              spacing: 4,
              runSpacing: 4,
              children: [
                ...'QWERTYUIOPASDFGHJKLZXCVBNM'.split('').map((letter) {
                  return ElevatedButton(
                    onPressed: () => addLetter(letter),
                    child: Text(letter),
                  );
                }),
                ElevatedButton(
                  onPressed: removeLetter,
                  style:
                      ElevatedButton.styleFrom(backgroundColor: Colors.orange),
                  child: Text('Delete'),
                ),
                ElevatedButton(
                  onPressed: submitWord,
                  style:
                      ElevatedButton.styleFrom(backgroundColor: Colors.green),
                  child: Text('Enter'),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
